import { test, expect } from '@playwright/test'

for (const locale of ['en', 'ar']) {
  test(`${locale}: compact setup, evidence scope and return-to-draft on a phone`, async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 812 })
    await page.goto(`/${locale}/draft-coach/`)
    const window = page.locator('.coach-essentials select').first()
    await expect(window).toHaveValue('14')
    await expect(page.locator('.coach-board')).toBeHidden()
    await expect(page.locator('.coach-advanced')).not.toHaveAttribute('open', '')
    await window.selectOption('season')
    const allCount = Number(await page.locator('.coach-proof__stats b').innerText())
    await window.selectOption('14')
    expect(Number(await page.locator('.coach-proof__stats b').innerText())).toBeLessThanOrEqual(allCount)
    await page.locator('.coach-start').click()
    await expect(page.locator('#coach-settings')).toBeHidden()
    await expect(page.locator('.coach-recommendation').first()).toBeVisible()
    const box = await page.locator('.coach-arena__topbar').boundingBox()
    expect(box!.y).toBeGreaterThanOrEqual(0)
    expect(box!.y).toBeLessThan(150)
    const before = await page.locator('.coach-arena__topbar').innerText()
    await page.locator('.coach-settings-toggle').first().click()
    await expect(page.locator('#coach-settings')).toBeVisible()
    await page.locator('.coach-settings-toggle').last().click()
    expect(await page.locator('.coach-arena__topbar').innerText()).toBe(before)
    expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1)
    await page.screenshot({ path: `test-results/coach-workspace-${locale}-mobile.png`, fullPage: false })
  })
}

test('observed cores expose source games and can be selected without making a pick', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/en/draft-coach/')
  await page.screenshot({ path: 'test-results/coach-workspace-en-desktop.png' })
  await page.locator('.coach-playbook > summary').click()
  const core = page.locator('.coach-blueprint').first()
  await expect(core).toBeVisible()
  await core.locator('details > summary').click()
  const source = core.locator('a').first()
  await expect(source).toHaveAttribute('href', /^https:\/\/liquipedia.net\/mobilelegends\//)
  await expect(source).toContainText(/2026-\d\d-\d\d/)
  await core.getByRole('button').click()
  await expect(page.locator('.coach-core-selection')).toContainText('Your preferred core')
  await expect(page.locator('.coach-arena__topbar')).toContainText('Ready to start')
  await page.locator('.coach-start').click()
  const coreHeroes = await core.locator('.coach-blueprint__heroes strong').allTextContents()
  const banHeroes = await page.locator('.coach-recommendation__name strong').allTextContents()
  expect(banHeroes.some((hero) => coreHeroes.includes(hero))).toBe(false)
  const selected = (await core.locator('.coach-blueprint__heroes strong').first().innerText()).trim()
  // Manually ban a chosen core hero: preference must be explicitly suspended.
  await page.getByTitle(new RegExp(`^${selected.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')} ·`)).click()
  await expect(page.locator('.coach-core-selection')).toContainText('ranking bonus is paused')
  await page.locator('.coach-core-selection button').click()
  await expect(page.locator('.coach-core-selection')).toHaveCount(0)
})

test('regional recommendations carry regional counts and no tier-list badges', async ({ page }) => {
  await page.goto('/en/draft-coach/')
  await page.locator('.coach-region-rail').getByRole('button', { name: /Philippines/ }).click()
  await page.locator('.coach-data-scope summary').click()
  await expect(page.locator('.coach-data-scope a')).toHaveCount(1)
  await expect(page.locator('.coach-data-scope a')).toContainText('Philippines')
  await page.locator('.coach-start').click()
  await page.locator('.coach-evidence summary').first().click()
  await expect(page.locator('.coach-evidence[open]')).toContainText('selected region, map and date window')
  await expect(page.locator('.coach-recommendations')).not.toContainText('Patch SS')
})
